yetanalytics/lrsql

.dockerignore
.github/workflows/build.yml
Dockerfile
README.md
doc/docker.md
doc/index.md
docker-compose.yml

[SQL-121] Prepare for public Docker Release
Please review the docs page here: https://github.com/yetanalytics/lrsql/blob/docker_release/doc/docker.md
Note that the current image is pushed to `yetanalytics/lrsql:latest` so you can follow along with the doc instructions.
[SQL-121]: https://yet.atlassian.net/browse/SQL-121

Docker Release

---

deps.edn

The colossal-squuid library was updated to fix a multi-threading bug. The lrsql dep will have to be updated in order to address it.

Update colossal-squuid dep in response to bugfix

---

README.md

Make the Docker badge more consistent with the Docker(hub) color scheme, and also because blue is a nicer color than orange in my opinion.

Change docker badge color from orange to blue

---

doc/docker.md

It occurred to me that the simple Docker example we give is effectively ephemeral, since the data is only written within the container. This PR modifies the example run command to include a bind mount so data will persist. A named volume is used so we don't have to worry about absolute paths, and the example "just works".

Add persistent Sqlite volume to Docker example.

---

deps.edn

Update the lrs and xapi-schema deps to fix the following bugs:
- IOException on POSTing Statements with Attachments
- CI failure due to `:result/score` spec generation failure

Update lrs and xapi-schema deps

---

deps.edn

Update core LRS lib to 1.1.3, which includes updates to multipart handling + statement unsigning. See the [changelog](https://github.com/yetanalytics/lrs/blob/master/CHANGELOG.md#113---2021-11-10) for more info
* Multipart handling fails if two attachments in the same POST share a SHA
* Multipart handling fails if two attachments in the same GET share a SHA
* Statement Signature unsigning comparison doesn't use immut statement comparison
See:
* https://github.com/yetanalytics/lrs/pull/67
* https://github.com/yetanalytics/lrs/pull/65
1. Start a lrsql instance at port 8080
2. Start a second instance at port 8081
3. run an xapipe connection between them:
```shell
bin/run.sh --source-url http://0.0.0.0:8080/xapi \
--source-username <key> \
--source-password <secret> \
--target-url …
```

latest LRS v1.1.3

---

resources/lrsql/config/test/default/webserver.edn
src/main/lrsql/system/webserver.clj
src/test/lrsql/concurrency_test.clj
src/test/lrsql/conformance_test.clj
src/test/lrsql/https_test.clj
src/test/lrsql/lrs_test.clj

`add-xapi-interceptors` accepts `path-prefix`, not `url-prefix` as the arg to change the URL path prefix (e.g. `host:port/xapi`).

[SQL-126] Change `url-prefix` to `path-prefix`

---

Makefile
deps.edn

fixed an issue in chrome 95+ that froze because of a CSS attr. Updated lrs and admin-ui deps

LRS-60 Chrome Crash issue

---

deps.edn
src/main/logback.xml
src/main/lrsql/admin/routes.clj
src/main/lrsql/input/statement.clj
src/main/lrsql/system/database.clj
src/main/lrsql/system/util.clj
src/main/lrsql/system/webserver.clj
src/main/lrsql/util/interceptor.clj
src/test/lrsql/admin/route_test.clj
src/test/lrsql/util/config_test.clj

- Redact sensitive info before logging config var maps
- ~Turn off Pedestal logging since we can't redact info from that~ (Made redundant by https://github.com/yetanalytics/lrs/pull/71)
- Return 400 instead of 500 error (which spews out exn info) upon JSONParseException
- ~TODO: Write tests for the above~ Done!

[SQL-125] Redact sensitive information from traces

---

.github/workflows/build.yml
.java_modules
Dockerfile
Makefile

- Added crypto module to java modules for custom JREs because of SSL issue
- Added `.java_modules` list
- Updated runtimer usage to use re-usable workflow
- Switched to locally generated runtime for dev
- Updated Dockerfile to use modules list

updated module list. upgraded runtimer usage to reusable workflow

---

deps.edn
doc/sqlite.md
doc/startup.md
src/db/h2/lrsql/h2/sql/ddl.sql
src/test/lrsql/lrs_test.clj

Update since v1.4.200 is no longer supported and to address CVE-2021-23463.
**NOTE:** This update is **not** backwards compatible (if using H2) due to changes in SQL syntax and to the underlying database file.

[SQL-129] Update H2 from v1.4.200 to v2.0.202

---

deps.edn

Addresses CVE-2021-42392 and CVE-2022-23221

Update H2 to version 2.1.210 to fix vulnerabilities

---

resources/lrsql/config/config.edn
src/main/lrsql/spec/config.clj
src/test/lrsql/test_support.clj

This PR adds a key to the `:database` config called `:test-db-version` which will be used (in tests ONLY) to set the version of PG testcontainers provides for fixtures.

add tc version via config

---

deps.edn

For scan failure: https://github.com/yetanalytics/lrsql/runs/5640486174?check_suite_focus=true
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
https://github.com/FasterXML/jackson-databind/issues/2816

Update jackson-core to 2.13.2 to address CVE-2020-36518

---

Makefile
doc/env_vars.md
resources/lrsql/config/prod/default/webserver.edn
resources/lrsql/config/test/default/webserver.edn
resources/lrsql/config/test/oidc/webserver.edn
src/main/lrsql/admin/interceptors/oidc.clj
src/main/lrsql/admin/interceptors/ui.clj
src/main/lrsql/admin/routes.clj
src/main/lrsql/init/oidc.clj
src/main/lrsql/spec/config.clj
src/main/lrsql/system/webserver.clj

[SQL-144] When started with settings to provide admin OIDC access, the `LRSQL_OIDC_ENABLE_LOCAL_ADMIN` flag determines whether or not local admin accounts will still be allowed to do things.
[SQL-144]: https://yet.atlassian.net/browse/SQL-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-144 OIDC local admin toggle

---

deps.edn

- Update Postgres to v42.3.3 to address [CVE-2022-21724](https://nvd.nist.gov/vuln/detail/CVE-2022-21724).
- Update Testcontainers to v1.16.3 to match PG version.

Update Postgres to address CVE

---

deps.edn
src/db/h2/lrsql/h2/record.clj
src/db/postgres/lrsql/postgres/record.clj
src/db/sqlite/lrsql/sqlite/record.clj
src/main/lrsql/system/util.clj
src/main/lrsql/util.clj

Update HugSql to v0.5.3 to take advantage of SQL file reads and function definitions now being evaluated at compile-time.

[SQL-146] HugSql update

---

deps.edn
src/main/lrsql/ops/query/statement.clj
src/test/lrsql/lrs_test.clj

[LRS-72] Handle deduplicated attachments introduced in https://github.com/yetanalytics/lrs/pull/81
Additionally, deduplicates outbound attachments per guidance in the `lrs` [README](https://github.com/yetanalytics/lrs#get-statements).
[LRS-72]: https://yet.atlassian.net/browse/LRS-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LRS-72 lrs 1.2.10

---

.gitignore
.nvd/suppression.xml
deps.edn

- Add suppression to H2 false positive CVE ([CVE issue](https://github.com/h2database/h2database/issues/3175), [FP report](https://github.com/jeremylong/DependencyCheck/issues/4555))
- Update cheshire lib to 5.11.0 and remove manual exclusions + transitive deps

Fix NVD warnings and update deps

---

doc/authority.md
src/main/lrsql/util/statement.clj
src/test/lrsql/util/statement_test.clj

[SQL-150] SQL LRS currently does not overwrite authority with the operator-defined authority, a bug. This PR forces overwrite of all incoming statement authority objects.
[SQL-150]: https://yet.atlassian.net/browse/SQL-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-150 Overwrite Statement Authority

---

.nvd/suppression.xml
deps.edn

Also leave out websockets if possible, not used!
Adds suppression for CVE-2022-2191 due to incorrect advisory version range, see https://github.com/eclipse/jetty.project/issues/8161

bump jetty deps for CVE-2022-2048, CVE-2022-2047, CVE-2022-2191

---

deps.edn
src/test/lrsql/https_test.clj

Update Postgres JDBC driver to 42.4.1 in order to address CVE-2022-31197. Also update Testcontainers to 1.17.3 and fix an unrelated failing test on HTTPS.

Address Postgres CVE

---

src/main/lrsql/admin/interceptors/oidc.clj
src/main/lrsql/util/oidc.clj
src/test/lrsql/util/oidc_test.clj

Fix bug/security hole in `authorize-oidc-request` interceptor where `authorize-admin-action`'s result is always interpreted as true.

OIDC security fix

---

dev-resources/keycloak_demo/test-realm.json
doc/oidc.md
resources/lrsql/config/test/oidc/webserver.edn

* Updates all OIDC keycloak demo uris to use `localhost` instead of `0.0.0.0`
* Makes clients that don't tolerate that foolishness work
* Adds `lrs:statements/read/mine` scope to keycloak demo client scopes
* Replaces `lrs:all` default scope in `lrs_client` Client Credentials Grant demo with `lrs:statements/read/mine` and `lrs:statements/write`
To test:
1. `make keycloak-demo`
2. `make ephemeral-oidc`
3. In an Oauth 2.0 CCG-capable http client, use the client: `lrs_client`. Get its secret from the [keycloak UI](http://localhost:8081/auth/admin/master/console/). For the token URL, use `http://localhost:8081/auth/realms/test/protocol/openid-connect/token`

statements/read/mine OIDC demo

---

src/main/lrsql/init/authority.clj
src/main/lrsql/init/oidc.clj

Add validation to default non-OIDC authority template and all OIDC authority templates. OIDC templates must conform to 3-legged OAuth xAPI Groups.

Authority template validation

---

deps.edn

CVE-2022-41946 is back, baybee! Looks like `org.postgresql/postgresql@42.4.3` has been added to the vuln range, see [this change](https://nvd.nist.gov/vuln/detail/CVE-2022-41946/change-record?changeRecordedOn=11/28/2022T14:43:46.820-0500)

CVE-2022-41946 Redux

---

dev-resources/template/2_lrs.yml

Prevent untold ruin by forcing locale to `en_US.UTF-8` for the service. This prevents the application from choosing an incorrect encoding for PG json, which may suggest other code changes to SQL LRS to remove this unpredictable behavior.

Force Locale on `lrsql.service`

---

bin/run_h2.sh
bin/run_h2_persistent.sh
bin/run_postgres.sh
bin/run_sqlite.sh

Run script java args incorrectly carry the `-J` wrapping from the Clojure CLI. Correct this so run scripts (and thus docker) work.
See https://github.com/yetanalytics/lrsql/issues/263

SQL-160 correct run script java arg syntax

---

doc/env_vars.md
resources/lrsql/config/prod/default/webserver.edn
resources/lrsql/config/test/default/webserver.edn
src/main/lrsql/init/config.clj
src/main/lrsql/spec/config.clj
src/main/lrsql/system.clj
src/main/lrsql/system/webserver.clj
src/test/lrsql/admin/cors_test.clj
src/test/lrsql/test_support.clj

This enables CORS Support to be configurable. There are three possible running modes, defined by 2 variables:
- By default, with no additional settings, the allowed origins will be restricted to the `LRSQL_HTTP_HOST` setting, which is by default `0.0.0.0:[8080/8443]`
- If you set `LRSQL_ALLOW_ALL_ORIGINS` to `true`, it will ignore and just approve everything (legacy mode)
- If you explicitly set origins using `LRSQL_ALLOWED_ORIGINS` it will restrict to those. in ENV thats a comma-separated list, in JSON its an array.

CORS Configuration Support

---

src/main/lrsql/system/webserver.clj
src/test/lrsql/admin/cors_test.clj

[SQL-163] With no CORS allowed origins specified, `localhost` should be a valid origin. This PR adds it to the default list with the given HTTP/S ports.
[SQL-163]: https://yet.atlassian.net/browse/SQL-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-163 localhost-friendly CORS defaults

---

dev-resources/template/2_lrs.yml
doc/aws.md

[SQL-165] The CF template needs some love, specifically in the form of CORS settings.
The logic is now as follows: If the template is given the CORSAllowedOrigins param, these are used. If not, the ALBHostname is used, if it is not present no web origins are allowed.
[SQL-165]: https://yet.atlassian.net/browse/SQL-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-165 Add CORS for CF template

---

src/db/postgres/lrsql/postgres/sql/query.sql

[SQL-176] We're getting an error when the timeline query runs on PG 12+
When we add `AS` it works. This is a hotfix to get PG 12 working pending matrix testing of PG versions.
[SQL-176]: https://yet.atlassian.net/browse/SQL-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-176 add AS to postgresql timeline query so it doesn't error on 12+

---

.github/workflows/test.yml
Makefile
doc/dev.md
doc/postgres.md
resources/lrsql/config/config.edn

[SQL-177] We support all current maintained versions of PG but do not test them in CI. This PR adds targets to the makefile to explicitly test each version. Note that the existing `test-postgres` target will run the earliest version, 11.
Note that the _current minor_ version of each major version will run.
The `LRSQL_TEST_DB_VERSION` env var determines which version will be run in TestContainers. Any Postgres docker tag (ex. `latest`) is valid. The default is `11`.
[SQL-177]: https://yet.atlassian.net/browse/SQL-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-177 Test against all supported versions of PostgreSQL

---

dev-resources/template/1_db.yml

* Add `DBInstancePublic` boolean parameter, if `true` will make DB instances publicly accessible
* Add `DBInstanceReplica` boolean parameter, if `true` will add a 2nd DB instance
Also sets the default engine to `14.3` and makes the default instance `db.r5.large` which is a working combo.

SQL-181 RDS template updates

---

doc/oidc.md
doc/startup.md
src/db/h2/lrsql/h2/record.clj
src/db/h2/lrsql/h2/sql/query.sql
src/db/postgres/lrsql/postgres/record.clj
src/db/postgres/lrsql/postgres/sql/query.sql
src/db/sqlite/lrsql/sqlite/record.clj
src/db/sqlite/lrsql/sqlite/sql/query.sql
src/main/lrsql/admin/interceptors/account.clj
src/main/lrsql/admin/protocol.clj
src/main/lrsql/backend/protocol.clj
src/main/lrsql/input/admin.clj
src/main/lrsql/ops/command/admin.clj
src/main/lrsql/spec/admin.clj
src/main/lrsql/system/lrs.clj
src/test/lrsql/admin/protocol_test.clj

[SQL-186] Prevent deletion of an admin account if it is the only one on the system. Allow deletion if the LRS is hooked up to OIDC.
[SQL-186]: https://yet.atlassian.net/browse/SQL-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-186 Prevent deletion of sole admin account

---

Makefile
src/db/h2/lrsql/h2/record.clj
src/db/h2/lrsql/h2/sql/query.sql
src/db/h2/lrsql/h2/sql/update.sql
src/db/postgres/lrsql/postgres/record.clj
src/db/postgres/lrsql/postgres/sql/query.sql
src/db/postgres/lrsql/postgres/sql/update.sql
src/db/sqlite/lrsql/sqlite/record.clj
src/db/sqlite/lrsql/sqlite/sql/query.sql
src/db/sqlite/lrsql/sqlite/sql/update.sql
src/main/lrsql/admin/interceptors/account.clj
src/main/lrsql/admin/protocol.clj
src/main/lrsql/admin/routes.clj
src/main/lrsql/backend/protocol.clj
src/main/lrsql/input/admin.clj
src/main/lrsql/ops/command/admin.clj
src/main/lrsql/ops/query/admin.clj
src/main/lrsql/spec/admin.clj
src/main/lrsql/system/lrs.clj
src/test/lrsql/admin/protocol_test.clj
src/test/lrsql/admin/route_test.clj

[SQL-187] Allow updates to local admin passwords. Admin must provide old password to update.
[SQL-187]: https://yet.atlassian.net/browse/SQL-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-187 Feature: Update Local Admin Password

---

src/main/lrsql/backend/protocol.clj

It was in a protocol declaration so it didn't really mess anything up, but still.

Fixed typo in protocol method

---

src/main/lrsql/util/cert.clj

- Switched certgen to bouncycastle. It's cleaner anyway
Can anyone who reviews this please test it on whatever random JDKs they have locally? Over here I've done openjdk11 and 16.0/20

[SQL-192] - later Java version support

---

src/test/lrsql/conformance_test.clj

This was needed after the lrs-conformance-test repo was updated to 2.0.0, which uses xAPI version 2.0.0.0 as its default

Add `-x 1.0.3` flag to conformance tests

---

src/main/lrsql/util/concurrency.clj

sleep long cast fix for jdk16+

sleep long cast fix for jdk16+

---

src/main/lrsql/ops/query/reaction.clj
src/main/lrsql/ops/util/reaction.clj
src/main/lrsql/spec/reaction.clj
src/test/lrsql/ops/util/reaction_test.clj

Added another condition to make sure only statements prior to trigger are used, in case a batch insert or another thread inserts while trigger is waiting to be processed. This necessitated updating a bunch of tests and stuff.

Reaction batch insert concurrency issue

---

doc/env_vars.md
resources/lrsql/config/config.edn
resources/lrsql/config/prod/sqlite_mem/connection.edn
resources/lrsql/config/test/sqlite_mem/connection.edn

When a HikariCP (or any JDBC connection) is closed, the entire database is deleted, as explained in [this article](https://grishaev.me/en/clj-sqlite/):
> The thing is, JDBC does not track DB connections by default. Every time you call for (jdbc/*) function, you create a new connection, perform an operation and close it. For such persistent data storages like Postgres or MySQL that’ fine although not effective (in our project, we use HikariCP to have a pool of open connections).
>
> **But for in-memory SQLite database, closing a connection to it leads to wiping the data completely out form the RAM.** So you need to track the connection in more precision way. You will create a connection by yourself and close it when the work is done.
In HikariCP, a connection is open for the duration of …

Fix in-memory SQLite bug where DB is deleted upon connection close

---

deps.edn
doc/env_vars.md

Update Logback to 1.3.14 to address CVE-2023-6481. Note that the underlying vulnerability was actually fixed in the previous update, but we still need to update for a more complete fix. From the [Logback website](https://logback.qos.ch/news.html#1.3.14):
> More complete fix for CVE-2023-6378 both for the 1.4.x series and the 1.3.x series...In order to encourage users to upgrade to versions 1.3.14/1.4.14 CVE-2023-6481 has been created even though the underlying vulnerability for both CVE records is identical.
In addition, we update the config variable name `maxLifetime` to `poolMaxLifetime` in the documentation, to address a naming oversight from the last update.

Update Logback to 1.3.14

---

src/main/lrsql/util/reaction.clj
src/test/lrsql/util/reaction_test.clj

[SQL-211] Previously identityPaths would not resolve if any were not found. Now they will resolve if _at least one_ is found.
[SQL-211]: https://yet.atlassian.net/browse/SQL-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-211 make identityPaths fuzzier

---

src/main/lrsql/ops/util/reaction.clj
src/main/lrsql/util/reaction.clj
src/test/lrsql/util/reaction_test.clj

[SQL-224] Encode condition names so invalid SQL is not produced.
[SQL-224]: https://yet.atlassian.net/browse/SQL-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-224 Reactions: encode condition names

---

src/main/lrsql/ops/query/reaction.clj

Refactoring for Backend Reaction Code

Reactions Refactoring

---

deps.edn

Updates the Cheshire library to 5.12.0 to use the latest version of Jackson.

Update Cheshire to 5.12.0

---

Makefile
doc/env_vars.md
resources/lrsql/config/prod/default/webserver.edn
resources/lrsql/config/test/default/webserver.edn
src/main/lrsql/admin/interceptors/ui.clj
src/main/lrsql/admin/routes.clj
src/main/lrsql/spec/config.clj
src/main/lrsql/system/webserver.clj

[SQL-230] When the `jwt-no-val-*` config options are used, `jwt-no-val-logout-url` specifies a URL to redirect to on logout.
~~[UI PR](https://github.com/yetanalytics/lrs-admin-ui/pull/68)~~
[SQL-230]: https://yet.atlassian.net/browse/SQL-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-230 add logout redirect url

---

src/main/lrsql/admin/interceptors/jwt.clj

[SQL-231] If no-val mode is used and no token is present or is malformed we can get an NPE and a 500 response. This change puts a try/catch around the token decoding code that leads to a 401 if there is not a valid token, rather than the 500.
[SQL-231]: https://yet.atlassian.net/browse/SQL-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQL-231 catch token exceptions in no-val mode

---

deps.edn

Address the critical vulnerability CVE-2024-1597 via Postgres JDBC driver update. This vulnerability can be exploited if the user sets a particular parameter in the JBDC URL, which our configuration allows the user to do.

Address CVE-2024-1597 via Postgres JDBC driver update

---

.github/workflows/test.yml
.nvd/suppression.xml
deps.edn

Update Pedestal to 0.6.3, address CVE-2024-22201, and remove unused NVD suppressions.

Pedestal CVE updates

---

deps.edn

The core team has added mitigation for CVE-2024-22871. Version 1.11.2 of Clojure contains this.

update to latest clojure to resolve CVE-2024-22871

---

src/main/lrsql/spec/statement.clj
src/test/lrsql/params_test.clj

The `from` parameter for Statement queries was not validated due to it not being an xAPI spec-defined parameter. As a result, if the value of `from` was invalid, this would result in a 500 Internal Server Error instead of a 400 Bad Request error.

[SQL-239] `from` parameter validation

---

Dockerfile

upgraded alpine to 3.19.1 in order to get openjdk 11.0.22* runtime

Docker image OS upgrade

---

src/main/lrsql/admin/interceptors/ui.clj
src/main/lrsql/init/localization.clj

Using a def should AOT-compile the custom language map, which we don't want. It doesn't appear to do this in practice, but an explicit memoization of the function will ensure that the language map is customizable at any level of complilation

memoize custom lang map fn

---

src/main/lrsql/backend/data.clj
src/main/lrsql/system/webserver.clj
src/main/lrsql/util.clj
src/main/lrsql/util/reaction.clj
src/test/lrsql/util/reaction_test.clj

I noticed there were a bunch of clj-kondo errors and warnings, so I addressed them by changing out deprecated functions, adding ignores, and removing redundant imports.

Fix clj-kondo errors and warnings

---

deps.edn
src/main/lrsql/util/statement.clj
src/test/lrsql/util/statement_test.clj

- Update the underlying xapi-schema lib version to allow for empty language maps in xAPI Statements
- Despite the above, automatically remove empty maps in xAPI Statements (lang maps, `context`, `result`, and Activity `definition`) before insertion

Empty language maps

---

src/db/postgres/lrsql/postgres/record.clj
src/db/postgres/lrsql/postgres/sql/ddl.sql
src/test/lrsql/lrs_test.clj

##Postgres only
Migrate from VARCHAR(255) to unlimited TEXT field to avoid insert errors for ridiculously long IRIs.
Must drop actor_ifi indexes and constraints and rebuild to convert. The rest are trivial

Migration from PG VARCHAR to TEXT

---

src/db/sqlite/lrsql/sqlite/record.clj
src/db/sqlite/lrsql/sqlite/sql/ddl.sql
src/dev/lrsql/user.clj

Ensure all migration queries return 1 vs null, rather than more detailed values. This change only applies in SQLite since Postgres queries are all already like this.
Based on this comment: https://github.com/yetanalytics/lrsql/pull/407#discussion_r1644877445

Simplify SQLite migration queries

---

Dockerfile

keep container lean.
No need to recut release right now, as its not a priority, just didnt want to forget before the next release.

Docker remove bench

---

deps.edn

patch commons-io to 2.14.0 to resolve CVE-2024-47554
Resolves https://github.com/yetanalytics/lrsql/security/dependabot/17

patch commons-io to 2.14.0 to resolve CVE-2024-47554

---

.github/workflows/build.yml
.github/workflows/deps.yml
.github/workflows/nvd.yml
.github/workflows/test.yml

Update most actions and reusable workflows:
- actions/checkout to v4
- actions/download-artifact to v4
- actions/upload-artifact to v4
- softprops/action-gh-release to v2
- JamesIves/github-pages-deploy-action to v4.6.4
- docker/login-action to v3
- docker/metadata-action to v5
- docker/build-push-action to v6 (jump update from v3)
- yetanalytics/action-setup-env to v2
- yetanalytics/workflow-nvd to v2
- yetanalytics/[workflow-]runtimer to v1 (in new repo)
- yetanalytics/workflow-linter to v2024.08.01
Leave the following action un-updated, however:
- advanced-security/maven-dependency-submission-action to v4, as this has [additional breaking changes](https://github.com/advanced-security/maven-dependency-submission-action/releases/tag/v4.0.0) besides Node updates
Testing of the release …

Update GitHub Actions

---

deps.edn
src/main/lrsql/spec/statement.clj
src/test/lrsql/lrs_test.clj
src/test/lrsql/scope_test.clj

This adds a test for POST with empty list

[LRS-83] POST with empty list

---

.nvd/suppression.xml
deps.edn

Small PR to address the following CVEs:
- CVE-2024-6763: Suppress since our code does not utilize the HttpURI class, which is how the vulnerability is exposed
- CVE-2024-8184: Update Jetty to 9.4.56.v20240826

Jetty CVE fixes

---

.nvd/suppression.xml

Apparently additional Jetty deps have been flagged as being assocciated with CVE-2024-6763, so this update suppresses that CVE for all Jetty packages. This is still a suppression since we ultimately want to update to Jetty 12 at some point in the future.

Suppress additional CVE-2024-6763 warnings

---

.github/workflows/build.yml

Update the version of the workflow-runtimer reusable workflow in order to update to Ubuntu 22.04 and MacOS 14; the latter is critical due to MacOS 12 being deprecated in GitHub Actions.

Update workflow-runtimer version

---

deps.edn
src/test/lrsql/lrs_test.clj

This PR illustrates a bug with SQL LRS where certain activity definition fields can be "forgotten" when multiple instances of an activity enter the LRS, one without a definition and one with. While the name and description fields appear to be preserved, the `type` field does not.
I've modified `stmt-1` in the lrs tests to have an activity type to show the issue. Note that when `stmt-0` (without a definition) precedes `stmt-1` (with a definition), the resulting activity query is missing the type field. When it is the other way around, `stmt-1` preceding `stmt-0`, the type field shows up.
The issue is resolved by updating the `lrs` lib's `merge-activity` function to allow updates to all definition fields, and to atomically update interaction activity fields.

Activity Definition Upsert

---

doc/index.md

fix link in docs

---

doc/endpoints.md
src/main/lrsql/admin/interceptors/account.clj
src/main/lrsql/admin/routes.clj
src/test/lrsql/admin/route_test.clj

Add an `/admin/verify` endpoint* that returns a bodyless `204 OK` response when the current JWT is authenticated. This is essentially the `/admin/me` endpoint but without the body. This will be useful for the client to use when polling the server to check if the user is currently authenticated.
Also add `/admin/openapi` and `/admin/status` to the endpoint docs since for some reason they were not included before.
NOTE: name may be subject to change based on suggestions

[SQL-267] `/admin/verify` endpoint

---

doc/endpoints.md
src/db/postgres/lrsql/postgres/record.clj
src/db/postgres/lrsql/postgres/sql/ddl.sql
src/db/postgres/lrsql/postgres/sql/delete.sql
src/db/postgres/lrsql/postgres/sql/insert.sql
src/db/postgres/lrsql/postgres/sql/query.sql
src/db/sqlite/lrsql/sqlite/record.clj
src/db/sqlite/lrsql/sqlite/sql/ddl.sql
src/db/sqlite/lrsql/sqlite/sql/delete.sql
src/db/sqlite/lrsql/sqlite/sql/insert.sql
src/db/sqlite/lrsql/sqlite/sql/query.sql
src/main/lrsql/admin/interceptors/account.clj
src/main/lrsql/admin/interceptors/jwt.clj
src/main/lrsql/admin/protocol.clj
src/main/lrsql/admin/routes.clj
src/main/lrsql/backend/protocol.clj
src/main/lrsql/input/admin/jwt.clj
src/main/lrsql/ops/command/admin.clj
src/main/lrsql/ops/query/admin.clj
src/main/lrsql/spec/admin/jwt.clj
src/main/lrsql/system/lrs.clj
src/main/lrsql/util.clj
src/main/lrsql/util/admin.clj
src/test/lrsql/admin/protocol_test.clj
src/test/lrsql/admin/route_test.clj
src/test/lrsql/input/input_test.clj
src/test/lrsql/util/admin_test.clj

Implement a `/admin/account/logout` endpoint that revokes the user's current JWT. The revocation is implemented using a blocklist implemented in the SQL database, that is purged of expired tokens whenever the user performs a login or logout.
The blocklist expiration is determined by `LRSQL_JWT_EXP_TIME`, since that is the shorted time interval the revocation can safely last (otherwise if we revoke a JWT immediately after it's issued, but un-revoke it before the token expires via blocklist purging, then the revocation becomes pointless).
Important refactors:
- Extracted out JWT decoding and verification functions from `validate-jwt` interceptor
- JWT decoding functions now return maps instead of scalars
- Surround admin route tests with try-finally blocks

[SQL-222] Admin logout endpoint

---

src/main/lrsql/admin/interceptors/ui.clj
src/main/lrsql/admin/routes.clj

Update the base UI path to `/admin/ui`, and have it return the `index.html` directly rather than having it redirect to `/admin/index.html`. This will prevent clashing from other `/admin` endpoints, which is important for more detailed paths such as `/admin/ui/credentials` (which will be implemented using [re-route](https://github.com/yetanalytics/re-route) in the frontend).

Update base UI path to `/admin/ui`

---

src/main/lrsql/admin/routes.clj

Currently there is a bug where Reactions cannot be accessed when the user is logged in with OIDC/Keycloak.

Allow Reactions with OIDC login

---

src/db/postgres/lrsql/postgres/record.clj
src/db/postgres/lrsql/postgres/sql/ddl.sql
src/db/postgres/lrsql/postgres/sql/insert.sql
src/db/postgres/lrsql/postgres/sql/query.sql
src/db/postgres/lrsql/postgres/sql/update.sql
src/db/sqlite/lrsql/sqlite/record.clj
src/db/sqlite/lrsql/sqlite/sql/ddl.sql
src/db/sqlite/lrsql/sqlite/sql/insert.sql
src/db/sqlite/lrsql/sqlite/sql/query.sql
src/db/sqlite/lrsql/sqlite/sql/update.sql
src/main/lrsql/admin/interceptors/account.clj
src/main/lrsql/admin/interceptors/jwt.clj
src/main/lrsql/admin/interceptors/lrs_management.clj
src/main/lrsql/admin/protocol.clj
src/main/lrsql/admin/routes.clj
src/main/lrsql/backend/protocol.clj
src/main/lrsql/input/admin/jwt.clj
src/main/lrsql/ops/command/admin.clj
src/main/lrsql/ops/query/admin.clj
src/main/lrsql/spec/admin/jwt.clj
src/main/lrsql/system/lrs.clj
src/main/lrsql/util/admin.clj
src/test/lrsql/admin/protocol_test.clj
src/test/lrsql/admin/route_test.clj
src/test/lrsql/bench_test.clj
src/test/lrsql/input/input_test.clj
src/test/lrsql/util/admin_test.clj

Implement authentication for the `GET /admin/csv` endpoint, as HTML `download` attributes cannot have headers, thus making the usual JWT authentication impossible.
We introduce the concept of "one-time JWTs" that have "one-time IDs." These one-time JWTs are stored in the `jwt_blocklist` SQL table (added in v0.8.0), where if the `one_time_id` column is not null then they are ignored during the query for blocked JWTs. Thus, these JWTs can easily be blocked/revoked by updating `one_time_id` to be null, which happens once they are validated. These one-time JWTs can be added as a `token` parameter for any GET endpoint, this case the CSV download endpoint.

[SQL-283] Authentication for CSV export

---

src/db/postgres/lrsql/postgres/record.clj
src/db/postgres/lrsql/postgres/sql/ddl.sql

- added a check to resolve[ issue #476](https://github.com/yetanalytics/lrsql/issues/476), where startup could be slow when the reapplication of jsonb triggered rebuild of custom B-tree indexes, even after conversion

Skip setting payload type if already correct

---

Makefile
deps.edn
resources/lrsql/config/config.edn
resources/lrsql/config/test/maria/connection.edn
src/dev/lrsql/user.clj
src/test/logback-test.xml
src/test/lrsql/test_runner.clj
src/test/lrsql/test_support.clj
src/test/lrsql/test_support_test.clj

Rather than running containers per-test, run a single container and clear it after every test.
To run individual tests in the repl, use set-db-fixture-mode! to set your desired backend first and then containers will be created on-demand.

Speed Up Tests with Singleton TestContainer
