yetanalytics/lrsql

README.md
A simple docker badge via [shields.io](shields.io)
=> Docker badge

README.md
=> contributor covenant badge

Makefile
=> admin ui upgrade to v0.1.2

Makefile
See: https://github.com/yetanalytics/lrs-admin-ui/pull/31
=> Update Admin UI dep to v0.1.5

deps.edn
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
=> CVE-2020-36518 again

README.md, doc/authority.md, doc/oidc.md
[SQL-141] Make some good documentation for OIDC functionality.
[Doc Page](https://github.com/yetanalytics/lrsql/blob/SQL-141/doc/oidc.md)
[SQL-141]: https://yet.atlassian.net/browse/SQL-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-141 OIDC docs

deps.edn
Make sure it works with a snapshot first...
=> get lrs from clojars

.github/workflows/build.yml, .github/workflows/nvd.yml
- Separate out release from build procedure into its own job
- Add Slack notification for periodic NVD scan and limit it to weekdays
=> CI and CD improvements

deps.edn
[This PR](https://github.com/yetanalytics/lrs/pull/83) improves attachment parsing. Update to latest `lrs`.
=> LRS-75 Improved Attachment Parsing

doc/env_vars.md, resources/lrsql/config/config.edn, src/main/lrsql/init/config.clj, src/main/lrsql/init/log.clj, src/main/lrsql/system.clj, src/main/lrsql/system/logger.clj
[SQL-154] Per https://github.com/yetanalytics/lrsql/issues/237, provide a simple way for users to set the runtime log level.
[SQL-154]: https://yet.atlassian.net/browse/SQL-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-154 allow runtime log level control with env var

deps.edn
=> CVE-2022-41946

README.md
=> correct superset README link

dev-resources/template/2_lrs.yml, doc/aws.md
[SQL-166] Add cloudwatch logs and metrics
[SQL-166]: https://yet.atlassian.net/browse/SQL-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-166 add Cloudwatch Metrics + Logs to template

deps.edn
Update LRS version for bumped commons-fileupload
=> CVE-2023-24998 commons-fileupload vuln

.nvd/suppression.xml
See https://github.com/jeremylong/DependencyCheck/issues/5502
=> CVE-2022-45688 add suppression for false positive on jackson

dev-resources/template/2_lrs.yml, doc/aws.md
[SQL-182] from prying eyes
[SQL-182]: https://yet.atlassian.net/browse/SQL-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-182 Set NoEcho on DefaultAdminPass to hide it

.github/workflows/deps.yml, Makefile
[SQL-183] Push deps to GitHub to allow SBOM creation
[SQL-183]: https://yet.atlassian.net/browse/SQL-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-183 GitHub Dependency Graph

deps.edn
[PS-199]
[PS-199]: https://yet.atlassian.net/browse/PS-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ps-199] clj, conflicting deps and DS update

src/main/lrsql/util/reaction.clj, src/test/lrsql/util/reaction_test.clj
[SQL-193]
[SQL-193]: https://yet.atlassian.net/browse/SQL-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-193 Statement Generation FN

src/db/sqlite/lrsql/sqlite/record.clj, src/db/sqlite/lrsql/sqlite/sql/ddl.sql, src/db/sqlite/lrsql/sqlite/sql/query.sql, src/main/lrsql/admin/protocol.clj, src/main/lrsql/backend/protocol.clj, src/main/lrsql/ops/query/reaction.clj, src/main/lrsql/ops/util/reaction.clj, src/main/lrsql/spec/reaction.clj, src/main/lrsql/system/lrs.clj, src/main/lrsql/util/reaction.clj, src/test/lrsql/admin/protocol_test.clj, src/test/lrsql/ops/query/reaction_test.clj, src/test/lrsql/ops/util/reaction_test.clj, src/test/lrsql/test_constants.clj, src/test/lrsql/test_support.clj, src/test/lrsql/util/reaction_test.clj
[SQL-198] Create a reaction function to produce reaction statements to a submitted statement.
[SQL-198]: https://yet.atlassian.net/browse/SQL-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-198 Reaction Function

src/db/sqlite/lrsql/sqlite/record.clj, src/db/sqlite/lrsql/sqlite/sql/ddl.sql, src/db/sqlite/lrsql/sqlite/sql/delete.sql, src/db/sqlite/lrsql/sqlite/sql/query.sql, src/db/sqlite/lrsql/sqlite/sql/update.sql, src/main/lrsql/backend/protocol.clj, src/main/lrsql/input/reaction.clj, src/main/lrsql/ops/command/reaction.clj, src/main/lrsql/ops/query/reaction.clj, src/main/lrsql/reaction/protocol.clj, src/main/lrsql/spec/reaction.clj, src/main/lrsql/system/lrs.clj, src/main/lrsql/util/reaction.clj, src/test/lrsql/ops/query/reaction_test.clj, src/test/lrsql/ops/util/reaction_test.clj, src/test/lrsql/reaction/protocol_test.clj
[SQL-200] Finish core reaction transaction function. Store errors when they happen and disable reactions with errors.
[SQL-200]: https://yet.atlassian.net/browse/SQL-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-200 Reaction TX Function & Errors

src/db/sqlite/lrsql/sqlite/record.clj, src/main/lrsql/backend/data.clj, src/main/lrsql/input/reaction.clj, src/main/lrsql/ops/query/reaction.clj, src/main/lrsql/ops/util/reaction.clj, src/main/lrsql/spec/common.clj, src/main/lrsql/spec/reaction.clj, src/main/lrsql/util.clj, src/main/lrsql/util/reaction.clj, src/test/lrsql/reaction/protocol_test.clj, src/test/lrsql/util/reaction_test.clj, src/test/lrsql/util/util_test.clj
[SQL-202] To the extent possible, use built-in facilities to (de)serialize reactions.
[SQL-202]: https://yet.atlassian.net/browse/SQL-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-202 Implicit DB serialization

.dir-locals.el, src/bench/lrsql/bench.clj
[SQL-203] Benchmark statement insertion timings.
[SQL-203]: https://yet.atlassian.net/browse/SQL-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-203 Bench Insert Timings

src/main/lrsql/admin/interceptors/ui.clj, src/main/lrsql/admin/routes.clj
[SQL-211] Let the front end know whether or not we are using reactions
[SQL-211]: https://yet.atlassian.net/browse/SQL-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-211 provide reactions toggle to FE env

src/db/postgres/lrsql/postgres/record.clj, src/db/postgres/lrsql/postgres/sql/ddl.sql, src/db/postgres/lrsql/postgres/sql/insert.sql, src/db/postgres/lrsql/postgres/sql/query.sql, src/db/postgres/lrsql/postgres/sql/update.sql, src/db/sqlite/lrsql/sqlite/record.clj, src/db/sqlite/lrsql/sqlite/sql/ddl.sql, src/db/sqlite/lrsql/sqlite/sql/insert.sql, src/db/sqlite/lrsql/sqlite/sql/query.sql, src/db/sqlite/lrsql/sqlite/sql/update.sql, src/main/lrsql/admin/interceptors/reaction.clj, src/main/lrsql/admin/protocol.clj, src/main/lrsql/input/reaction.clj, src/main/lrsql/ops/command/reaction.clj, src/main/lrsql/ops/query/reaction.clj, src/main/lrsql/spec/reaction.clj, src/main/lrsql/system/lrs.clj, src/test/lrsql/admin/protocol_test.clj, src/test/lrsql/admin/route_test.clj, src/test/lrsql/lrs_test.clj, src/test/lrsql/ops/query/reaction_test.clj, src/test/lrsql/ops/util/reaction_test.clj, src/test/lrsql/reaction/protocol_test.clj
[SQL-212] Add a unique, editable and required title field to reactions.
[SQL-212]: https://yet.atlassian.net/browse/SQL-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-212 Reaction Title

Makefile, deps.edn, dev-resources/clamav/attachment_body.txt, dev-resources/clamav/docker-compose.yml, doc/docker.md, doc/env_vars.md, docker-compose.yml, resources/lrsql/config/prod/default/webserver.edn, resources/lrsql/config/test/default/webserver.edn, src/main/lrsql/init/clamav.clj, src/main/lrsql/spec/config.clj, src/main/lrsql/system/webserver.clj, src/test/lrsql/scan_test.clj
[SQL-215] Enable ClamAV scanning for attachments and documents.
[SQL-215]: https://yet.atlassian.net/browse/SQL-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-215 ClamAV Antivirus Scanning

deps.edn
Update Logback to 1.3.13 to address CVE-2023-6378
=> Update Logback to 1.3.13

deps.edn
Needs to use clojars once proven
=> ContextActivities change to xapi-schema

src/main/lrsql/admin/routes.clj, src/test/lrsql/lrs_test.clj, src/test/lrsql/ops/query/reaction_test.clj, src/test/lrsql/reaction/protocol_test.clj, src/test/lrsql/test_constants.clj
Update body-params to not try to parse strings as qualified keywords.
=> Reacrtions: fix keyword chopping bug

doc/reactions.md
Add a simple example of reaction input + output to the doc
=> reaction doc example

Makefile
Update to the latest lrs-admin-ui with better handing of server-side exceptions.
=> Update to v0.0.16 of lrs-admin-ui

README.md, doc/general_faq.md, doc/overview.md, doc/troubleshooting.md
Create "General Questions" and "Troubleshooting" FAQ pages.
=> Add troubleshooting FAQ to docs

deps.edn
=> clear CVE-2024-29857, CVE-2024-30172, CVE-2024-30171

Makefile, src/main/lrsql/admin/interceptors/ui.clj, src/main/lrsql/admin/routes.clj, src/main/lrsql/system/webserver.clj
- Added statement get max to env call
=> SQL-244 Support for table view in data browser

dev-resources/load_balanced/docker-compose.yml
* Use an internal volume so state on the disk doesn't confuse things on multiple runs
* ~~Add `restart: always` to LRS svcs~~ This is fixed by Cliff's hc dependency stuff
=> Docker Tweaks

deps.edn
https://github.com/yetanalytics/lrsql/security/dependabot/15
https://github.com/yetanalytics/lrsql/security/dependabot/14
https://github.com/yetanalytics/lrsql/security/dependabot/13
=> update bcpkix to 1.78

docker-compose.yml
- Change DB's bind mount to a named volume
- Expose DB's `5432` port
- Add a `LRSQL_ALLOW_ALL_ORIGINS` config vars (set it to `false` by default though, to avoid an extra breaking change)
=> `docker-compose.yml` update

dev-resources/template/2_lrs.yml
Adds the following params to the template:
* ASGHealthCheckGracePeriod
* InstanceCreationPolicyResourceSignalTimeout
* ASGCreationPolicyResourceSignalTimeout
* ASGUpdatePolicyAutoScalingRollingUpdatePauseTime
=> Additional Template Knobs

dev-resources/template/2_lrs.yml, src/main/lrsql/init.clj
Log on Migrations, Allow setting level on AWS
=> Log on Migrations, Allow setting level on AWS

Makefile
update to lrs-admin-ui v0.1.22 with statement browser refresh
=> update to lrs-admin-ui v0.1.22 with statement browser refresh

dev-resources/proxied_example/docker-compose.yml, dev-resources/proxied_example/nginx.conf
demo of nginx proxy with path working with sql lrs
=> proxy example with addtl path

deps.edn
Patch logback-classic for CVE-2024-12798
=> Patch logback-classic for CVE-2024-12798

doc/dev.md
Checklist for special scenarios that may need to be covered during manual integration testing.
Note that this list is not exhaustive; if there are any scenarios I missed please let me know.
=> Development checklist

Makefile
Forgot to update the UI version in #456 so this is the update.
=> Update UI version to v0.2.0

Makefile
See: https://github.com/yetanalytics/lrs-admin-ui/pull/109
=> [SQL-286] Update to UI version with timestamp fix

.github/workflows/test.yml, Makefile
Drop PostgreSQL versions 11 and 12, add testing for 17.
=> Update PG testing range

deps.edn
bump jetty dep to fix CVE-2025-5115
=> bump jetty dep to fix CVE-2025-5115
